
```{r}
x <- 1:10
```

```{r}
plot(x)
```

Now I'm writing some prose.  How awesome is that?

It's really cool I have to say.

```{r}
library(tidyverse)
```

```{r}
data <- read_tsv("~/Downloads/GSE11209_RAW/snyder.tsv", 
                 col_names = c("Chrom", "Start","End", "Seq", "Count", "Strand"))
```

```{r}
str(data)
```

```{r}
data <- 
  mutate(data, Midpoint = (Start+End)/2)
```

```{r}
ggplot(data, aes(x = Midpoint, y = Count)) + 
  geom_line(size=1, alpha=0.5) + 
  ylim(0,8)
```

```{r}
coords <- c()
for (i in 1:length(data$Start)) {
  coords <- c(coords, data$Start[i]:data$End[i])
}
```

```{r}
df <- tibble(coords = coords)

ggplot(df, aes(x = coords)) + 
  geom_histogram(bins=500) + 
    ylim(0,300) +
  scale_y_continuous(trans = "log2") 

```

```{r}
tableS4 <- read_excel("~/Desktop/TableS4.xls")
ts4 <- 
  rename(tableS4,expression = `Transcription_level(log2)`) |>
  mutate(Midpoint = (SGD_Start + SGD_End)/2)
```

```{r}
library(RColorBrewer)

display.brewer.pal(9, "Reds")  
color.scheme <- brewer.pal(9,"Reds")
```


```{r}
ts4 |>
  filter(Chrom == "chrI", SGD_Start > 100000, SGD_End < 150000) |>
ggplot(aes(x = SGD_Start, y = Chrom, width = SGD_End - SGD_Start, 
           fill = expression, height=0.5)) + 
    scale_fill_stepsn(colors=color.scheme,
                         limits = c(0, 10),
                         na.value = color.scheme[1]) +
  geom_tile()
```


